# Generated by Django 4.0.6 on 2022-07-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(default='', upload_to='')),
                ('ascii_text', models.TextField(default='')),
                ('braille_format', models.TextField(default='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
