# Generated by Django 4.0.6 on 2022-07-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibraille', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='img_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
