# Generated by Django 4.0.6 on 2022-07-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibraille', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vibrailleuser',
            name='veri_str_email',
            field=models.CharField(default='47966', max_length=5),
        ),
        migrations.AddField(
            model_name='vibrailleuser',
            name='veri_str_phone',
            field=models.CharField(default='52975', max_length=5),
        ),
        migrations.AddField(
            model_name='vibrailleuser',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vibrailleuser',
            name='verified_phone',
            field=models.BooleanField(default=False),
        ),
    ]
